stages:
    - setup
    - doc
    - pdf
    - pages

variables:
    GIT_SUBMODULE_STRATEGY: recursive

image: $CI_REGISTRY_IMAGE

setup:
    stage: setup
    image: docker:stable
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - docker build -t $CI_REGISTRY_IMAGE -f Dockerfile .
        - docker push $CI_REGISTRY_IMAGE

doc:
    stage: doc
    script:
        - LD_LIBRARY_PATH=/usr/lib/llvm-7/lib sphinx-build -b html doc/sdd html_sdd
        - LD_LIBRARY_PATH=/usr/lib/llvm-7/lib sphinx-build -b html doc/sum html_sum
        - LD_LIBRARY_PATH=/usr/lib/llvm-7/lib sphinx-build -b latex doc/sdd latex_sdd
        - LD_LIBRARY_PATH=/usr/lib/llvm-7/lib sphinx-build -b latex doc/sum latex_sum
        - chmod -R 777 latex_sdd
        - chmod -R 777 latex_sum
    artifacts:
        paths:
            - html_sdd/
            - html_sum/
            - latex_sdd/
            - latex_sum/
        expire_in: 30 days
    needs: ["setup"]

pdf:
    stage: pdf
    image: local.gtd-gmbh.de:4567/tools/doge:latest
    dependencies:
        - doc
    script:
        - cd latex_sdd
        - make
        - mv ./libmcs-sdd.pdf ../.
        - cd ../latex_sum
        - make
        - mv ./libmcs-sum.pdf ../.
    artifacts:
        paths:
            - ./*.pdf
        expire_in: 30 days
    needs: ["doc"]

pages:
  stage: pages
  image:
    name: pandoc/core:2.16.2
    entrypoint: [""]
  dependencies:
      - doc
  needs: ["doc"]
  script:
    - mkdir public
    - cp doc/index.html public
    - pandoc -s -o public/README.html --metadata title="LibmCS Readme" README.md
    - mv html_sum public/sum
    - mv html_sdd public/sdd
  artifacts:
    paths:
      - public
